# Generated by Django 2.2.1 on 2019-06-08 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Palace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Palace credentials',
                'verbose_name_plural': 'Palace credentials',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default=None, max_length=7)),
                ('street_number', models.CharField(max_length=5)),
                ('street_name', models.CharField(max_length=40)),
                ('suburb', models.CharField(max_length=50)),
                ('city', models.CharField(default='Auckland', max_length=20)),
                ('postcode', models.IntegerField(null=True)),
                ('code', models.CharField(max_length=11)),
                ('change_code', models.IntegerField(default=1)),
                ('publish_entry', models.CharField(default=None, max_length=3)),
                ('date_available', models.CharField(max_length=35)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('carparks', models.IntegerField(blank=True, null=True)),
                ('property_class', models.CharField(blank=True, max_length=15)),
                ('is_new_construction', models.CharField(blank=True, default=False, max_length=3)),
                ('pets', models.CharField(max_length=3)),
                ('smokers', models.CharField(max_length=3)),
                ('agent_email1', models.EmailField(max_length=254)),
                ('agent_email2', models.EmailField(max_length=254)),
                ('agent_name', models.CharField(max_length=50)),
                ('agent_mobile_num', models.CharField(max_length=15)),
                ('agent_work_num', models.CharField(max_length=15)),
                ('rental_period', models.CharField(default='Week', max_length=6)),
                ('rent', models.IntegerField()),
                ('advert_text', models.TextField(blank=True, max_length=2000)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/property_images')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, null=True, upload_to='media/property_images')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.Property')),
            ],
        ),
    ]
