# Generated by Django 2.1.3 on 2019-01-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_property_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(blank=True, default=None, upload_to='media/property_images'),
        ),
    ]
