# Generated by Django 2.1.3 on 2019-01-05 06:59

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190105_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, upload_to='media/property_images'),
        ),
    ]
