# Generated by Django 2.1.3 on 2019-01-05 07:07

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190105_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, default=None, upload_to='media/property_images'),
        ),
    ]
