# Generated by Django 2.1.3 on 2019-01-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190105_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='property_images'),
        ),
    ]
