# Generated by Django 2.1.3 on 2019-01-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20190114_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_class',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
