# Generated by Django 2.1.3 on 2019-01-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190115_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Palace credentials',
                'verbose_name_plural': 'Palace credentials',
            },
        ),
    ]
