# Generated by Django 2.1.5 on 2019-01-26 09:05

from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20190119_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default=None, upload_to='media/personnel/'),
        ),
    ]
