# Generated by Django 2.1.5 on 2019-01-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20190126_2205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-id'], 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
