# Generated by Django 2.1.5 on 2019-02-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_property_publish_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='publish_address',
            field=models.IntegerField(default=0),
        ),
    ]
