# Generated by Django 2.1.5 on 2019-02-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20190202_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='change_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='property',
            name='publish_address',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
