# Generated by Django 2.1.5 on 2019-02-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190202_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=False, upload_to='media/main_page')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Main page info',
                'verbose_name_plural': 'Main page info',
            },
        ),
    ]
