# Generated by Django 2.1.5 on 2019-02-03 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='MottoEmailPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(default='Your future starts with us', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='(09) 215 1267', max_length=12)),
            ],
            options={
                'verbose_name': 'Motto, email, and phone number',
                'verbose_name_plural': 'Motto, email, and phone number',
            },
        ),
    ]
