# Generated by Django 2.1.5 on 2019-02-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_mottoemailphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mottoemailphone',
            name='phone',
            field=models.CharField(default='(09) 215 1267', max_length=18),
        ),
    ]
