# Generated by Django 2.1.5 on 2019-02-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190203_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='publish_address',
            new_name='publish_entry',
        ),
    ]
