# Generated by Django 2.1.5 on 2019-02-04 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='ContactUs',
        ),
    ]
