# Generated by Django 2.1.5 on 2019-02-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_emailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='full_email',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
