# Generated by Django 2.1.5 on 2019-02-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_emailsettings_full_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='unit',
            field=models.CharField(default=None, max_length=7),
        ),
    ]
