# Generated by Django 2.1.5 on 2019-02-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20190210_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryPeroidocTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField(default=7200)),
            ],
            options={
                'verbose_name': 'Celery periodic tasks period',
                'verbose_name_plural': 'Celery periodic tasks period',
            },
        ),
    ]
