# Generated by Django 2.1.5 on 2019-02-24 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_celeryperoidoctask'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CeleryPeroidocTask',
            new_name='CeleryPeriodicTask',
        ),
    ]
