# Generated by Django 2.1.7 on 2019-03-01 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20190224_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CeleryPeriodicTask',
        ),
    ]
