# Generated by Django 2.1.7 on 2019-03-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_delete_celeryperiodictask'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Tenancy guide',
                'verbose_name_plural': 'Tenancy guide',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Why McDonald Property?',
                'verbose_name_plural': 'Why McDonald Property?',
            },
        ),
    ]
