# Generated by Django 2.1.7 on 2019-03-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_guide_whyus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(default=None, upload_to='media/personnel/'),
        ),
    ]
