# Generated by Django 2.1.7 on 2019-03-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20190313_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalAppraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100000)),
            ],
            options={
                'verbose_name': 'Rental appraisal',
                'verbose_name_plural': 'Rental appraisal',
            },
        ),
    ]
