# Generated by Django 2.2.1 on 2019-06-08 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About us',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact us',
                'verbose_name_plural': 'Contact us',
            },
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_email', models.CharField(default=None, max_length=60)),
                ('email_host', models.CharField(max_length=40)),
                ('email_port', models.PositiveIntegerField()),
                ('email_host_user', models.CharField(max_length=50)),
                ('email_host_password', models.CharField(max_length=50)),
                ('email_use_ssl', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Email settings',
                'verbose_name_plural': 'Email settings',
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=100000)),
            ],
            options={
                'verbose_name': 'Tenancy guide',
                'verbose_name_plural': 'Tenancy guide',
            },
        ),
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=False, upload_to='media/main_page')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Main page info',
                'verbose_name_plural': 'Main page info',
            },
        ),
        migrations.CreateModel(
            name='MottoEmailPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(default='Your future starts with us', max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='(09) 215 1267', max_length=18)),
                ('facebook', models.URLField(default='http://facebook.com')),
                ('linkedin', models.URLField(default='http://linkedin.com')),
            ],
            options={
                'verbose_name': 'Motto, email, and phone number',
                'verbose_name_plural': 'Motto, email, and phone number',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('about', models.TextField(max_length=1000)),
                ('image', models.ImageField(default=None, upload_to='media/personnel/')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000)),
            ],
            options={
                'verbose_name': 'Why McDonald Property?',
                'verbose_name_plural': 'Why McDonald Property?',
            },
        ),
    ]
